version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready  -d db123 -U user123"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" 

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy



